# 3. 도형그리기 
빈 스키치북 만들기

In [1]:
import cv2
import numpy as np

# 세로 480x640,3channel 에 대항하는 스케치북 
img = np.zeros((480,640,3),dtype=np.uint8)
img[:] = (255,255,255)
print(img)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


## 일부영역 색칠

In [3]:
import cv2
import numpy as np

img = np.zeros((480,640,3),dtype=np.uint8)
img[100:200,200:300] = (255,255,255)
#[세로영역,가로영역]
print(img)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


# 직선
직선의 종류(line type)
1. cv2.LINE_4 : 상하좌우 4 방향으로 연결된 선 
2. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된선 (기본값)
3. cv2.LINE_AA : 부드로운 선 (anti-aliasing)

In [6]:
import cv2 
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

COLOR = (0,255,255) # BGR
THICKNESS = 3 #두께 

cv2.line(img,(50,100),(400,50), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img,(50,200),(400,150), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img,(50,300),(400,250), COLOR, THICKNESS, cv2.LINE_8)
# 그릴 위치, 시작점, 끝 점, 색깔, 두께, 선 종류

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# 원

In [12]:
import cv2 
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

COLOR = (255,255,0) # BGR
RADIUS = 50 # 반지름 
THICKNESS = 10 #두께 

cv2.circle(img,(200,100), RADIUS, COLOR,THICKNESS, cv2.LINE_AA )# 속이 빈원
cv2.circle(img,(500,100), RADIUS, COLOR,cv2.FILLED, cv2.LINE_AA )# 속이 빈원
# 그릴 위치, 원의 중심점, 반지름, 색깔, 두께, 선 종류 
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# 사각형

In [14]:
import cv2 
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

COLOR = (0,255,0) # BGR
THICKNESS = 3 #두께 

cv2.rectangle(img, (100,100),(200,200), COLOR, THICKNESS)
cv2.rectangle(img, (400,100),(200,300), COLOR, cv2.FILLED)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# 다각형

In [27]:
import cv2 
import numpy as np

img = np.zeros((480,640,3), dtype=np.uint8)

COLOR = (0,0,255) # BGR
THICKNESS = 3 #두께 

pts1 = np.array([[100,100],[200,100],[100,200]])
pts2 = np.array([[200,100],[300,100],[300,200]])
ptslist = [pts1,pts2]

#cv2.polylines(img,[pts1], True, COLOR, THICKNESS, cv2.LINE_AA)
#cv2.polylines(img,[pts2], True, COLOR, THICKNESS, cv2.LINE_AA)
cv2.polylines(img, ptslist, True, COLOR, THICKNESS, cv2.LINE_AA)

pts3 = np.array([[[100,300],[200,300],[100,400]],[[200,300],[300,300],[300,400]]])
cv2.fillPoly(img, pts3,COLOR,cv2.LINE_AA)
# 꽉찬 다각형, 그릴 좌표들,색깔, 선종류 

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
